## Bubble Charts

- Bubble charts are very similar to scatter plots , except we now coney a third variable's information through the size of the markers
- We can also continue to add variable information by coloring points based on a category

In [1]:
import numpy as np
import pandas as pd
import plotly.offline as pyo
import plotly.graph_objs as go

In [2]:
df = pd.read_csv('Data/mpg.csv')
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [19]:
data = [go.Scatter(x=df['horsepower'],y=df['mpg'],text=df['name'],mode='markers',marker=dict(size=2*df['cylinders']))]

In [20]:
layout = go.Layout(title='Bubble Chart')

In [21]:
fig = go.Figure(data,layout)
pyo.plot(fig)

'temp-plot.html'

In [10]:
data = [go.Scatter(x=df['horsepower'],y=df['mpg'],text=df['name'],mode='markers',marker=dict(size=df['weight']//100))]

In [11]:
layout = go.Layout(title='Bubble Chart')

In [12]:
fig = go.Figure(data,layout)
pyo.plot(fig)

'temp-plot.html'

In [22]:
data = [go.Scatter(x=df['horsepower'],y=df['mpg'],text=df['name'],mode='markers',marker=dict(size=df['weight']//100,color=df['cylinders']))]

In [23]:
layout = go.Layout(title='Bubble Chart')
fig = go.Figure(data,layout)
pyo.plot(fig)

'temp-plot.html'

In [24]:
df = pd.read_csv('Data/mpg.csv')
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [28]:
data = [go.Scatter(x=df['displacement'],y=df['acceleration'],text=df['name'],mode='markers',marker=dict(size=df['weight']//400))]

In [29]:
layout = go.Layout(title='My Bubble',hovermode='closest')

In [30]:
fig = go.Figure(data,layout)
pyo.plot(fig)

'temp-plot.html'