### Plotly

- Matplotlib, Seaborn, Pandas produce static images.
- Plotly provides interactive visualization in the form of HTML
- Can't work with live data source
- Dash used to create live data source based on dashboards

  
- Scatter Plots
- Line Charts
- Bar Plot
- Bubble Plot
- Box Plot
- Histograms
- Distplots
- Heatmaps


### Installing Plotly
Use the Conda install plotly command. Visit the following link
https://anaconda.org/plotly/plotly

In [1]:
import pandas as pd
import numpy as np
import plotly.offline as pyo
import plotly.graph_objs as go

In [4]:
delivery = pd.read_csv('data/deliveries.csv')
matches = pd.read_csv('data/matches.csv')

In [3]:
delivery.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN

In [5]:
matches.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [7]:
ipl=delivery.merge(matches,left_on='match_id',right_on='id')
ipl.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,...,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen

### 1. ScatterPlot

### Scatter plots are drawn between to continous variables
### Problem :- We are going to draw a scatter plot between Batsman Avg(X axis) and
### Batsman Strike Rate(Y axis) of the top 50 batsman in IPL(All time)

##### Avg vs SR graph of Top 50 batsman(in terms of total runs)

##### Fetching a new dataframe with Top 50 batsman

In [12]:
ipl.groupby('batter').sum()

/var/folders/zc/fcrq35tj1y11zktl3108b93r0000gn/T/ipykernel_85919/3580168412.py:1: FutureWarning:

The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.

,match_id,inning,over,ball,batsman_runs,extra_runs,total_runs,is_wicket,id,result_margin,target_runs,target_overs
batter,,,,,,,,,,,,
A Ashish Reddy,137869458,277,3116,720,280,8,288,15,137869458,2578.0,28640.0,3920.0
A Badoni,690816280,672,6795,1882,634,54,688,26,690816280,10362.0,86434.0,9400.0
A Chandila,4136511,7,125,23,4,0,4,1,4136511,47.0,835.0,140.0
A Chopra,26324575,78,392,273,53,5,58,5,26324575,1215.0,11024.0,1480.0
A Choudhary,21652432,28,351,71,25,0,25,2,21652432,268.0,2870.0,400.0
...,...,...,...,...,...,...,...,...,...,...,...,...
Yashpal Singh,26278255,113,511,250,47,2,49,4,26278255,963.0,8866.0,1340.0
Younis Khan,2352133,14,14,25,3,0,3,1,2352133,287.0,1554.0,140.0
Yudhvir Singh,22687153,30,245,67,22,0,22,4,22687153,831.0,3430.0,320.0
Yuvraj Singh,1479111979,3287,25077,8162,2754,130,2884,109,1479111979,31126.0,356239.0,43328.4
Z Khan,77494251,226,2282,525,117,4,121,15,77494251,5914.0,24032.0,2820.0

In [16]:
ipl.groupby('batter')['batsman_runs'].sum().sort_values(ascending=False).head(50).index

Index(['V Kohli', 'S Dhawan', 'RG Sharma', 'DA Warner', 'SK Raina', 'MS Dhoni',
       'AB de Villiers', 'CH Gayle', 'RV Uthappa', 'KD Karthik', 'KL Rahul',
       'AM Rahane', 'F du Plessis', 'SV Samson', 'AT Rayudu', 'G Gambhir',
       'SR Watson', 'MK Pandey', 'SA Yadav', 'JC Buttler', 'KA Pollard',
       'RR Pant', 'YK Pathan', 'Shubman Gill', 'Q de Kock', 'SS Iyer',
       'RA Jadeja', 'WP Saha', 'DA Miller', 'BB McCullum', 'PA Patel',
       'GJ Maxwell', 'Yuvraj Singh', 'V Sehwag', 'MA Agarwal', 'Ishan Kishan',
       'N Rana', 'M Vijay', 'HH Pandya', 'SPD Smith', 'SE Marsh', 'AD Russell',
       'JH Kallis', 'DR Smith', 'RD Gaikwad', 'SR Tendulkar', 'RA Tripathi',
       'R Dravid', 'KS Williamson', 'AJ Finch'],
      dtype='object', name='batter')

In [19]:
top50

['V Kohli',
 'S Dhawan',
 'RG Sharma',
 'DA Warner',
 'SK Raina',
 'MS Dhoni',
 'AB de Villiers',
 'CH Gayle',
 'RV Uthappa',
 'KD Karthik',
 'KL Rahul',
 'AM Rahane',
 'F du Plessis',
 'SV Samson',
 'AT Rayudu',
 'G Gambhir',
 'SR Watson',
 'MK Pandey',
 'SA Yadav',
 'JC Buttler',
 'KA Pollard',
 'RR Pant',
 'YK Pathan',
 'Shubman Gill',
 'Q de Kock',
 'SS Iyer',
 'RA Jadeja',
 'WP Saha',
 'DA Miller',
 'BB McCullum',
 'PA Patel',
 'GJ Maxwell',
 'Yuvraj Singh',
 'V Sehwag',
 'MA Agarwal',
 'Ishan Kishan',
 'N Rana',
 'M Vijay',
 'HH Pandya',
 'SPD Smith',
 'SE Marsh',
 'AD Russell',
 'JH Kallis',
 'DR Smith',
 'RD Gaikwad',
 'SR Tendulkar',
 'RA Tripathi',
 'R Dravid',
 'KS Williamson',
 'AJ Finch']

In [21]:
new_ipl=ipl[ipl['batter'].isin(top50)]

In [22]:
new_ipl.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,...,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
5,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,6,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen

In [24]:
# Calculating SR
# SR=[(number of runs scored)/(number of balls played)]*100

runs=new_ipl.groupby('batter')['batsman_runs'].sum()
balls=new_ipl.groupby('batter')['batsman_runs'].count()

sr=(runs/balls)*100

#sr=sr.reset_index()
sr

batter
AB de Villiers    148.580442
AD Russell        164.224422
AJ Finch          123.349057
AM Rahane         120.321410
AT Rayudu         124.584527
BB McCullum       126.848592
CH Gayle          142.121729
DA Miller         134.684477
DA Warner         135.429986
DR Smith          132.279534
F du Plessis      133.071325
G Gambhir         119.665153
GJ Maxwell        150.488599
HH Pandya         139.691290
Ishan Kishan      132.797589
JC Buttler        142.238984
JH Kallis         105.936272
KA Pollard        140.457703
KD Karthik        131.353404
KL Rahul          131.050866
KS Williamson     122.952710
M Vijay           118.614130
MA Agarwal        128.255646
MK Pandey         117.366180
MS Dhoni          132.835065
N Rana            130.818859
PA Patel          116.625717
Q de Kock         131.120332
R Dravid          113.347237
RA Jadeja         124.432296
RA Tripathi       135.515152
RD Gaikwad        133.632791
RG Sharma         127.918194
RR Pant           143.597561
RV Uthappa        126.152279
S Dhawan          123.454313
SA Yadav          142.505948
SE Marsh          130.109775
SK Raina          132.535312
SPD Smith         124.812406
SR Tendulkar      114.187867
SR Watson         134.163209
SS Iyer           123.025540
SV Samson         135.137615
Shubman Gill      132.236842
V Kohli           128.511867
V Sehwag          148.827059
WP Saha           123.902027
YK Pathan         138.046272
Yuvraj Singh      124.784776
Name: batsman_runs, dtype: float64

In [25]:
sr=sr.reset_index()
sr

            batter  batsman_runs
0   AB de Villiers    148.580442
1       AD Russell    164.224422
2         AJ Finch    123.349057
3        AM Rahane    120.321410
4        AT Rayudu    124.584527
5      BB McCullum    126.848592
6         CH Gayle    142.121729
7        DA Miller    134.684477
8        DA Warner    135.429986
9         DR Smith    132.279534
10    F du Plessis    133.071325
11       G Gambhir    119.665153
12      GJ Maxwell    150.488599
13       HH Pandya    139.691290
14    Ishan Kishan    132.797589
15      JC Buttler    142.238984
16       JH Kallis    105.936272
17      KA Pollard    140.457703
18      KD Karthik    131.353404
19        KL Rahul    131.050866
20   KS Williamson    122.952710
21         M Vijay    118.614130
22      MA Agarwal    128.255646
23       MK Pandey    117.366180
24        MS Dhoni    132.835065
25          N Rana    130.818859
26        PA Patel    116.625717
27       Q de Kock    131.120332
28        R Dravid    113.347237
29       RA Jadeja    124.432296
30     RA Tripathi    135.515152
31      RD Gaikwad    133.632791
32       RG Sharma    127.918194
33         RR Pant    143.597561
34      RV Uthappa    126.152279
35        S Dhawan    123.454313
36        SA Yadav    142.505948
37        SE Marsh    130.109775
38        SK Raina    132.535312
39       SPD Smith    124.812406
40    SR Tendulkar    114.187867
41       SR Watson    134.163209
42         SS Iyer    123.025540
43       SV Samson    135.137615
44    Shubman Gill    132.236842
45         V Kohli    128.511867
46        V Sehwag    148.827059
47         WP Saha    123.902027
48       YK Pathan    138.046272
49    Yuvraj Singh    124.784776

In [27]:
# Calculating Avg
# Avg=(Total number of Runs)/(Number of outs)

# Calculating number of outs for top 50 batsman
out=ipl[ipl['player_dismissed'].isin(top50)]

nouts=out['player_dismissed'].value_counts()

avg=runs/nouts

avg=avg.reset_index()
avg.rename(columns={'index':'batter',0:'avg'},inplace=True)

avg=avg.merge(sr,on='batter')
avg

            batter        avg  batsman_runs
0   AB de Villiers  39.853846    148.580442
1       AD Russell  28.930233    164.224422
2         AJ Finch  24.904762    123.349057
3        AM Rahane  30.142857    120.321410
4        AT Rayudu  28.051613    124.584527
5      BB McCullum  27.711538    126.848592
6         CH Gayle  39.658730    142.121729
7        DA Miller  35.658537    134.684477
8        DA Warner  40.042683    135.429986
9         DR Smith  28.392857    132.279534
10    F du Plessis  35.992126    133.071325
11       G Gambhir  31.007353    119.665153
12      GJ Maxwell  24.750000    150.488599
13       HH Pandya  28.471910    139.691290
14    Ishan Kishan  28.430108    132.797589
15      JC Buttler  37.715789    142.238984
16       JH Kallis  28.552941    105.936272
17      KA Pollard  28.404959    140.457703
18      KD Karthik  26.320652    131.353404
19        KL Rahul  44.657143    131.050866
20   KS Williamson  35.533333    122.952710
21         M Vijay  25.930693    118.614130
22      MA Agarwal  22.811966    128.255646
23       MK Pandey  29.015038    117.366180
24        MS Dhoni  39.126866    132.835065
25          N Rana  28.344086    130.818859
26        PA Patel  22.603175    116.625717
27       Q de Kock  30.980392    131.120332
28        R Dravid  28.233766    113.347237
29       RA Jadeja  27.398148    124.432296
30     RA Tripathi  26.939759    135.515152
31      RD Gaikwad  41.754386    133.632791
32       RG Sharma  29.730942    127.918194
33         RR Pant  35.451613    143.597561
34      RV Uthappa  27.522222    126.152279
35        S Dhawan  35.072539    123.454313
36        SA Yadav  31.805310    142.505948
37        SE Marsh  39.507937    130.109775
38        SK Raina  32.374269    132.535312
39       SPD Smith  34.652778    124.812406
40    SR Tendulkar  33.826087    114.187867
41       SR Watson  30.793651    134.163209
42         SS Iyer  31.948980    123.025540
43       SV Samson  30.687500    135.137615
44    Shubman Gill  37.835294    132.236842
45         V Kohli  38.714976    128.511867
46        V Sehwag  27.555556    148.827059
47         WP Saha  24.247934    123.902027
48       YK Pathan  29.290909    138.046272
49    Yuvraj Singh  24.810811    124.784776

In [38]:
trace = go.Scatter(x=avg['avg'],y=avg['batsman_runs'],mode='markers',text=avg['batter'],marker={'color':'#99f66f','size':16})

In [39]:
data =[trace]
layout = go.Layout({'title':'Batsman Avg Vs SR'},xaxis={'title':'Bastman Average'},yaxis={'title':'Batsman Strike Rate'})
fig = go.Figure(data=data,layout=layout)
pyo.plot(fig,filename='myfile.html')

'myfile.html'

### Line Chart

#### Year by year batsman performance

In [41]:
single_batsman = ipl[ipl['batter']=='SR Tendulkar']
single_batsman

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,...,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
7153,336012,2,Mumbai Indians,Royal Challengers Bangalore,0,4,SR Tendulkar,A Kumble,ST Jayasuriya,1,...,field,Mumbai Indians,wickets,9.0,123.0,18.0,N,NaN,BF Bowden,AV Jayaprakash
7155,336012,2,Mumbai Indians,Royal Challengers Bangalore,0,6,SR Tendulkar,A Kumble,ST Jayasuriya,0,...,field,Mumbai Indians,wickets,9.0,123.0,18.0,N,NaN,BF Bowden,AV Jayaprakash
7163,336012,2,Mumbai Indians,Royal Challengers Bangalore,2,1,SR Tendulkar,P Kumar,ST Jayasuriya,0,...,field,Mumbai Indians,wickets,9.0,123.0,18.0,N,NaN,BF Bowden,AV Jayaprakash
7164,336012,2,Mumbai Indians,Royal Challengers Bangalore,2,2,SR Tendulkar,P Kumar,ST Jayasuriya,0,...,field,Mumbai Indians,wickets,9.0,123.0,18.0,N,NaN,BF Bowden,AV Jayaprakash
7165,336012,2,Mumbai Indians,Royal Challengers Bangalore,2,3,SR Tendulkar,P Kumar,ST Jayasuriya,0,...,field,Mumbai Indians,wickets,9.0,123.0,18.0,N,NaN,BF Bowden,AV Jayaprakash
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91467,598060,2,Mumbai Indians,Sunrisers Hyderabad,10,6,SR Tendulkar,NLTC Perera,KD Karthik,0,...,bat,Mumbai Indians,wickets,7.0,179.0,20.0,N,NaN,AK Chaudhary,SJA Taufel
91468,598060,2,Mumbai Indians,Sunrisers Hyderabad,10,7,SR Tendulkar,NLTC Perera,KD Karthik,1,...,bat,Mumbai Indians,wickets,7.0,179.0,20.0,N,NaN,AK Chaudhary,SJA Taufel
91469,598060,2,Mumbai Indians,Sunrisers Hyderabad,11,1,SR Tendulkar,KV Sharma,KD Karthik,4,...,bat,Mumbai Indians,wickets,7.0,179.0,20.0,N,NaN,AK Chaudhary,SJA Taufel
91470,598060,2,Mumbai Indians,Sunrisers Hyderabad,11,2,SR Tendulkar,KV Sharma,KD Karthik,1,...,bat,Mumbai Indians,wickets,7.0,179.0,20.0,N,NaN,AK Chaudhary,SJA Taufel
91472,598060,2,Mumbai Indians,Sunrisers Hyderabad,11,4,SR Tendulkar,KV Sharma,KD Karthik,6,...,bat,Mumbai Indians,wickets,7.0,179.0,20.0,N,NaN,AK Chaudhary,SJA Taufel

In [48]:
single_batsman1 = ipl[ipl['batter']=='MS Dhoni']
single_batsman1

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,...,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
265,335983,1,Chennai Super Kings,Kings XI Punjab,6,3,MS Dhoni,IK Pathan,MEK Hussey,1,...,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
268,335983,1,Chennai Super Kings,Kings XI Punjab,6,6,MS Dhoni,IK Pathan,MEK Hussey,1,...,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
269,335983,1,Chennai Super Kings,Kings XI Punjab,7,1,MS Dhoni,JR Hopes,MEK Hussey,0,...,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
1719,335989,1,Chennai Super Kings,Mumbai Indians,15,1,MS Dhoni,DJ Bravo,ML Hayden,0,...,field,Chennai Super Kings,runs,6.0,209.0,20.0,N,NaN,DJ Harper,GA Pratapkumar
1720,335989,1,Chennai Super Kings,Mumbai Indians,15,2,MS Dhoni,DJ Bravo,ML Hayden,4,...,field,Chennai Super Kings,runs,6.0,209.0,20.0,N,NaN,DJ Harper,GA Pratapkumar
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259777,1426306,2,Chennai Super Kings,Royal Challengers Bengaluru,18,2,MS Dhoni,LH Ferguson,RA Jadeja,1,...,field,Royal Challengers Bengaluru,runs,27.0,219.0,20.0,N,NaN,A Totre,KN Ananthapadmanabhan
259780,1426306,2,Chennai Super Kings,Royal Challengers Bengaluru,18,5,MS Dhoni,LH Ferguson,RA Jadeja,4,...,field,Royal Challengers Bengaluru,runs,27.0,219.0,20.0,N,NaN,A Totre,KN Ananthapadmanabhan
259781,1426306,2,Chennai Super Kings,Royal Challengers Bengaluru,18,6,MS Dhoni,LH Ferguson,RA Jadeja,1,...,field,Royal Challengers Bengaluru,runs,27.0,219.0,20.0,N,NaN,A Totre,KN Ananthapadmanabhan
259783,1426306,2,Chennai Super Kings,Royal Challengers Bengaluru,19,1,MS Dhoni,Yash Dayal,RA Jadeja,6,...,field,Royal Challengers Bengaluru,runs,27.0,219.0,20.0,N,NaN,A Totre,KN Ananthapadmanabhan
259784,1426306,2,Chennai Super Kings,Royal Challengers Bengaluru,19,2,MS Dhoni,Yash Dayal,RA Jadeja,0,...,field,Royal Challengers Bengaluru,runs,27.0,219.0,20.0,N,NaN,A Totre,KN Ananthapadmanabhan

In [42]:
performance = single_batsman.groupby('season')['batsman_runs'].sum().reset_index()
performance

    season  batsman_runs
0  2007/08           188
1     2009           364
2  2009/10           618
3     2011           553
4     2012           324
5     2013           287

In [49]:
performance1 = single_batsman1.groupby('season')['batsman_runs'].sum().reset_index()
performance1

     season  batsman_runs
0   2007/08           414
1      2009           332
2   2009/10           287
3      2011           392
4      2012           358
5      2013           461
6      2014           371
7      2015           372
8      2016           284
9      2017           290
10     2018           455
11     2019           416
12  2020/21           200
13     2021           114
14     2022           232
15     2023           104
16     2024           161

In [57]:
trace1 = go.Scatter(x=performance['season'],y=performance['batsman_runs'],mode='lines+markers',text=single_batsman['batter'],marker={'color':'#faa669'})
trace2 = go.Scatter(x=performance1['season'],y=performance1['batsman_runs'],mode='lines+markers',text=single_batsman1['batter'],marker={'color':'#faa999'})
data = [trace1,trace2]
layout = go.Layout({'title':'Year by Year performance of a batsman'},xaxis={'title':'Year'},yaxis={'title':'Runs'})
fig = go.Figure(data=data,layout=layout)
pyo.plot(fig)

'temp-plot.html'

### Bar Plot

#### Used to show the relationship between one categorical and one numerical


#### There are three types of Bar Graphs

- Nested Bar Graph
- Satcked Bar Graph
- Overlayed Bar Graph

In [59]:
top10=ipl.groupby('batter')['batsman_runs'].sum().sort_values(ascending=False).head(10).index.tolist()

In [61]:
top10

['V Kohli',
 'S Dhawan',
 'RG Sharma',
 'DA Warner',
 'SK Raina',
 'MS Dhoni',
 'AB de Villiers',
 'CH Gayle',
 'RV Uthappa',
 'KD Karthik']

In [63]:
top10_df=ipl[ipl['batter'].isin(top10)]
top10_df.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,...,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
132,335982,2,Royal Challengers Bangalore,Kolkata Knight Riders,1,2,V Kohli,I Sharma,W Jaffer,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
133,335982,2,Royal Challengers Bangalore,Kolkata Knight Riders,1,3,V Kohli,I Sharma,W Jaffer,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
134,335982,2,Royal Challengers Bangalore,Kolkata Knight Riders,1,4,V Kohli,I Sharma,W Jaffer,1,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
137,335982,2,Royal Challengers Bangalore,Kolkata Knight Riders,2,1,V Kohli,AB Dinda,W Jaffer,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
138,335982,2,Royal Challengers Bangalore,Kolkata Knight Riders,2,2,V Kohli,AB Dinda,W Jaffer,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen

In [65]:
top10_score=top10_df.groupby('batter')['batsman_runs'].sum().reset_index()
top10_score

           batter  batsman_runs
0  AB de Villiers          5181
1        CH Gayle          4997
2       DA Warner          6567
3      KD Karthik          4843
4        MS Dhoni          5243
5       RG Sharma          6630
6      RV Uthappa          4954
7        S Dhawan          6769
8        SK Raina          5536
9         V Kohli          8014

In [66]:
trace = go.Bar(x=top10_score['batter'],y=top10_score['batsman_runs'])

data = [trace]

layout = go.Layout(title='Top 10 IPL batter',xaxis={'title':'batter'},yaxis={'title':'score'})

fig = go.Figure(data=data,layout=layout)

pyo.plot(fig)

'temp-plot.html'

In [68]:
iw=top10_df.groupby(['batter','inning'])['batsman_runs'].sum().reset_index()
iw

            batter  inning  batsman_runs
0   AB de Villiers       1          3163
1   AB de Villiers       2          1999
2   AB de Villiers       3            13
3   AB de Villiers       4             6
4         CH Gayle       1          2873
5         CH Gayle       2          2092
6         CH Gayle       3            15
7         CH Gayle       4            10
8         CH Gayle       6             7
9        DA Warner       1          3280
10       DA Warner       2          3285
11       DA Warner       3             2
12       DA Warner       4             0
13      KD Karthik       1          2743
14      KD Karthik       2          2099
15      KD Karthik       4             1
16        MS Dhoni       1          3065
17        MS Dhoni       2          2178
18       RG Sharma       1          3600
19       RG Sharma       2          3028
20       RG Sharma       4             2
21      RV Uthappa       1          2120
22      RV Uthappa       2          2832
23      RV Uthappa       4             2
24        S Dhawan       1          3926
25        S Dhawan       2          2843
26        S Dhawan       4             0
27        SK Raina       1          3194
28        SK Raina       2          2334
29        SK Raina       3             8
30         V Kohli       1          4400
31         V Kohli       2          3604
32         V Kohli       4            10

In [69]:
mask=iw['inning']==1
mask2=iw['inning']==2

In [70]:
mask

0      True
1     False
2     False
3     False
4      True
5     False
6     False
7     False
8     False
9      True
10    False
11    False
12    False
13     True
14    False
15    False
16     True
17    False
18     True
19    False
20    False
21     True
22    False
23    False
24     True
25    False
26    False
27     True
28    False
29    False
30     True
31    False
32    False
Name: inning, dtype: bool

In [71]:
mask2

0     False
1      True
2     False
3     False
4     False
5      True
6     False
7     False
8     False
9     False
10     True
11    False
12    False
13    False
14     True
15    False
16    False
17     True
18    False
19     True
20    False
21    False
22     True
23    False
24    False
25     True
26    False
27    False
28     True
29    False
30    False
31     True
32    False
Name: inning, dtype: bool

In [72]:
one=iw[mask]
two=iw[mask2]

In [73]:
one

            batter  inning  batsman_runs
0   AB de Villiers       1          3163
4         CH Gayle       1          2873
9        DA Warner       1          3280
13      KD Karthik       1          2743
16        MS Dhoni       1          3065
18       RG Sharma       1          3600
21      RV Uthappa       1          2120
24        S Dhawan       1          3926
27        SK Raina       1          3194
30         V Kohli       1          4400

In [74]:
two

            batter  inning  batsman_runs
1   AB de Villiers       2          1999
5         CH Gayle       2          2092
10       DA Warner       2          3285
14      KD Karthik       2          2099
17        MS Dhoni       2          2178
19       RG Sharma       2          3028
22      RV Uthappa       2          2832
25        S Dhawan       2          2843
28        SK Raina       2          2334
31         V Kohli       2          3604

In [76]:
one.rename(columns={'batsman_runs':'1st Innings'},inplace=True)
two.rename(columns={'batsman_runs':'2nd Innings'},inplace=True)

final=one.merge(two,on='batter')[['batter','1st Innings','2nd Innings']]

final

/var/folders/zc/fcrq35tj1y11zktl3108b93r0000gn/T/ipykernel_85919/2535512716.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/zc/fcrq35tj1y11zktl3108b93r0000gn/T/ipykernel_85919/2535512716.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

           batter  1st Innings  2nd Innings
0  AB de Villiers         3163         1999
1        CH Gayle         2873         2092
2       DA Warner         3280         3285
3      KD Karthik         2743         2099
4        MS Dhoni         3065         2178
5       RG Sharma         3600         3028
6      RV Uthappa         2120         2832
7        S Dhawan         3926         2843
8        SK Raina         3194         2334
9         V Kohli         4400         3604

In [81]:
# Nested (By Default)

trace1 = go.Bar(x=final['batter'],y=final['1st Innings'],name='1st Innings',marker={'color':'#00a65a'})
trace2 = go.Bar(x=final['batter'],y=final['2nd Innings'],name='2nd Innings',marker={'color':'#00a65a'})

data = [trace1,trace2]

layout = go.Layout(title='Inning Wise Scores',xaxis={'title':'batter'},yaxis={'title':'score'})

fig = go.Figure(data=data,layout=layout)

pyo.plot(fig)

'temp-plot.html'

In [84]:
# Overlay

trace1 = go.Bar(x=final['batter'],y=final['1st Innings'],name='1st Innings',marker={'color':'#00a65a'})
trace2 = go.Bar(x=final['batter'],y=final['2nd Innings'],name='2nd Innings',marker={'color':'#99a65a'})

data = [trace1,trace2]

layout = go.Layout(title='Inning Wise Scores',xaxis={'title':'batter'},yaxis={'title':'score'},barmode='overlay')

fig = go.Figure(data=data,layout=layout)

pyo.plot(fig,filename='overlay.html')

'overlay.html'

In [85]:
# Stack

trace1 = go.Bar(x=final['batter'],y=final['1st Innings'],name='1st Innings',marker={'color':'#00a65a'})
trace2 = go.Bar(x=final['batter'],y=final['2nd Innings'],name='2nd Innings',marker={'color':'#99a65a'})

data = [trace1,trace2]

layout = go.Layout(title='Inning Wise Scores',xaxis={'title':'batter'},yaxis={'title':'score'},barmode='stack')

fig = go.Figure(data=data,layout=layout)

pyo.plot(fig)

'temp-plot.html'

## Bubble Plot

Extension of scatterplot with additional information

In [86]:
avg

            batter        avg  batsman_runs
0   AB de Villiers  39.853846    148.580442
1       AD Russell  28.930233    164.224422
2         AJ Finch  24.904762    123.349057
3        AM Rahane  30.142857    120.321410
4        AT Rayudu  28.051613    124.584527
5      BB McCullum  27.711538    126.848592
6         CH Gayle  39.658730    142.121729
7        DA Miller  35.658537    134.684477
8        DA Warner  40.042683    135.429986
9         DR Smith  28.392857    132.279534
10    F du Plessis  35.992126    133.071325
11       G Gambhir  31.007353    119.665153
12      GJ Maxwell  24.750000    150.488599
13       HH Pandya  28.471910    139.691290
14    Ishan Kishan  28.430108    132.797589
15      JC Buttler  37.715789    142.238984
16       JH Kallis  28.552941    105.936272
17      KA Pollard  28.404959    140.457703
18      KD Karthik  26.320652    131.353404
19        KL Rahul  44.657143    131.050866
20   KS Williamson  35.533333    122.952710
21         M Vijay  25.930693    118.614130
22      MA Agarwal  22.811966    128.255646
23       MK Pandey  29.015038    117.366180
24        MS Dhoni  39.126866    132.835065
25          N Rana  28.344086    130.818859
26        PA Patel  22.603175    116.625717
27       Q de Kock  30.980392    131.120332
28        R Dravid  28.233766    113.347237
29       RA Jadeja  27.398148    124.432296
30     RA Tripathi  26.939759    135.515152
31      RD Gaikwad  41.754386    133.632791
32       RG Sharma  29.730942    127.918194
33         RR Pant  35.451613    143.597561
34      RV Uthappa  27.522222    126.152279
35        S Dhawan  35.072539    123.454313
36        SA Yadav  31.805310    142.505948
37        SE Marsh  39.507937    130.109775
38        SK Raina  32.374269    132.535312
39       SPD Smith  34.652778    124.812406
40    SR Tendulkar  33.826087    114.187867
41       SR Watson  30.793651    134.163209
42         SS Iyer  31.948980    123.025540
43       SV Samson  30.687500    135.137615
44    Shubman Gill  37.835294    132.236842
45         V Kohli  38.714976    128.511867
46        V Sehwag  27.555556    148.827059
47         WP Saha  24.247934    123.902027
48       YK Pathan  29.290909    138.046272
49    Yuvraj Singh  24.810811    124.784776

In [88]:
top50 = ipl.groupby('batter')['batsman_runs'].sum().sort_values(ascending=False).head(50).index.to_list()
new_ipl = ipl[ipl['batter'].isin(top50)]
new_ipl

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,...,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
5,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,6,BB McCullum,P Kumar,SC Ganguly,0,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260763,1426312,1,Sunrisers Hyderabad,Kolkata Knight Riders,4,1,RA Tripathi,MA Starc,AK Markram,0,...,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon
260764,1426312,1,Sunrisers Hyderabad,Kolkata Knight Riders,4,2,RA Tripathi,MA Starc,AK Markram,0,...,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon
260910,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,8,6,SS Iyer,Shahbaz Ahmed,VR Iyer,4,...,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon
260915,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,AK Markram,VR Iyer,1,...,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon
260918,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,...,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon

In [90]:
new_ipl = new_ipl[new_ipl['batsman_runs']==6]
new_ipl

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,...,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
10,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,4,BB McCullum,Z Khan,SC Ganguly,6,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
20,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,3,2,BB McCullum,AA Noffke,SC Ganguly,6,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
25,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,3,7,BB McCullum,AA Noffke,SC Ganguly,6,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
60,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,9,5,BB McCullum,SB Joshi,RT Ponting,6,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
69,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,11,2,BB McCullum,SB Joshi,RT Ponting,6,...,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260254,1426310,1,Royal Challengers Bengaluru,Rajasthan Royals,1,5,F du Plessis,Sandeep Sharma,V Kohli,6,...,field,Rajasthan Royals,wickets,4.0,173.0,20.0,N,NaN,KN Ananthapadmanabhan,MV Saidharshan Kumar
260262,1426310,1,Royal Challengers Bengaluru,Rajasthan Royals,3,1,V Kohli,Avesh Khan,F du Plessis,6,...,field,Rajasthan Royals,wickets,4.0,173.0,20.0,N,NaN,KN Ananthapadmanabhan,MV Saidharshan Kumar
260402,1426310,2,Rajasthan Royals,Royal Challengers Bengaluru,6,1,SV Samson,Swapnil Singh,YBK Jaiswal,6,...,field,Rajasthan Royals,wickets,4.0,173.0,20.0,N,NaN,KN Ananthapadmanabhan,MV Saidharshan Kumar
260506,1426311,1,Sunrisers Hyderabad,Rajasthan Royals,3,4,RA Tripathi,R Ashwin,TM Head,6,...,field,Sunrisers Hyderabad,runs,36.0,176.0,20.0,N,NaN,Nitin Menon,VK Sharma
260509,1426311,1,Sunrisers Hyderabad,Rajasthan Royals,4,1,RA Tripathi,TA Boult,TM Head,6,...,field,Sunrisers Hyderabad,runs,36.0,176.0,20.0,N,NaN,Nitin Menon,VK Sharma

In [94]:
six = new_ipl.groupby('batter')['batsman_runs'].count().reset_index()
six

            batter  batsman_runs
0   AB de Villiers           253
1       AD Russell           209
2         AJ Finch            78
3        AM Rahane           103
4        AT Rayudu           173
5      BB McCullum           130
6         CH Gayle           359
7        DA Miller           134
8        DA Warner           236
9         DR Smith           117
10    F du Plessis           166
11       G Gambhir            59
12      GJ Maxwell           160
13       HH Pandya           137
14    Ishan Kishan           119
15      JC Buttler           161
16       JH Kallis            44
17      KA Pollard           224
18      KD Karthik           161
19        KL Rahul           187
20   KS Williamson            64
21         M Vijay            91
22      MA Agarwal            98
23       MK Pandey           111
24        MS Dhoni           252
25          N Rana           132
26        PA Patel            49
27       Q de Kock           123
28        R Dravid            28
29       RA Jadeja           107
30     RA Tripathi            84
31      RD Gaikwad            91
32       RG Sharma           281
33         RR Pant           154
34      RV Uthappa           182
35        S Dhawan           153
36        SA Yadav           130
37        SE Marsh            78
38        SK Raina           204
39       SPD Smith            60
40    SR Tendulkar            29
41       SR Watson           190
42         SS Iyer           113
43       SV Samson           206
44    Shubman Gill            95
45         V Kohli           273
46        V Sehwag           106
47         WP Saha            87
48       YK Pathan           161
49    Yuvraj Singh           149

In [96]:
ipl_six = avg.merge(six,on='batter')
ipl_six

            batter        avg  batsman_runs_x  batsman_runs_y
0   AB de Villiers  39.853846      148.580442             253
1       AD Russell  28.930233      164.224422             209
2         AJ Finch  24.904762      123.349057              78
3        AM Rahane  30.142857      120.321410             103
4        AT Rayudu  28.051613      124.584527             173
5      BB McCullum  27.711538      126.848592             130
6         CH Gayle  39.658730      142.121729             359
7        DA Miller  35.658537      134.684477             134
8        DA Warner  40.042683      135.429986             236
9         DR Smith  28.392857      132.279534             117
10    F du Plessis  35.992126      133.071325             166
11       G Gambhir  31.007353      119.665153              59
12      GJ Maxwell  24.750000      150.488599             160
13       HH Pandya  28.471910      139.691290             137
14    Ishan Kishan  28.430108      132.797589             119
15      JC Buttler  37.715789      142.238984             161
16       JH Kallis  28.552941      105.936272              44
17      KA Pollard  28.404959      140.457703             224
18      KD Karthik  26.320652      131.353404             161
19        KL Rahul  44.657143      131.050866             187
20   KS Williamson  35.533333      122.952710              64
21         M Vijay  25.930693      118.614130              91
22      MA Agarwal  22.811966      128.255646              98
23       MK Pandey  29.015038      117.366180             111
24        MS Dhoni  39.126866      132.835065             252
25          N Rana  28.344086      130.818859             132
26        PA Patel  22.603175      116.625717              49
27       Q de Kock  30.980392      131.120332             123
28        R Dravid  28.233766      113.347237              28
29       RA Jadeja  27.398148      124.432296             107
30     RA Tripathi  26.939759      135.515152              84
31      RD Gaikwad  41.754386      133.632791              91
32       RG Sharma  29.730942      127.918194             281
33         RR Pant  35.451613      143.597561             154
34      RV Uthappa  27.522222      126.152279             182
35        S Dhawan  35.072539      123.454313             153
36        SA Yadav  31.805310      142.505948             130
37        SE Marsh  39.507937      130.109775              78
38        SK Raina  32.374269      132.535312             204
39       SPD Smith  34.652778      124.812406              60
40    SR Tendulkar  33.826087      114.187867              29
41       SR Watson  30.793651      134.163209             190
42         SS Iyer  31.948980      123.025540             113
43       SV Samson  30.687500      135.137615             206
44    Shubman Gill  37.835294      132.236842              95
45         V Kohli  38.714976      128.511867             273
46        V Sehwag  27.555556      148.827059             106
47         WP Saha  24.247934      123.902027              87
48       YK Pathan  29.290909      138.046272             161
49    Yuvraj Singh  24.810811      124.784776             149

In [98]:
trace = go.Scatter(x=ipl_six['avg'],y=ipl_six['batsman_runs_x'],mode='markers',text=avg['batter'],marker={'color':ipl_six['batsman_runs_y'],'size':ipl_six['batsman_runs_y']})
data =[trace]
layout = go.Layout({'title':'Batsman Avg Vs SR'},xaxis={'title':'Bastman Average'},yaxis={'title':'Batsman Strike Rate'})
fig = go.Figure(data=data,layout=layout)
pyo.plot(fig,filename='myfile.html')

'myfile.html'

## Box Plot

- A box and whisker plot also called as box plot.
- Displays the 5 number summary of the set of data
- For numerical data only

In [101]:
match_agg = delivery.groupby('match_id')['total_runs'].sum().reset_index()
match_agg

      match_id  total_runs
0       335982         304
1       335983         447
2       335984         261
3       335985         331
4       335986         222
...        ...         ...
1090   1426307         429
1091   1426309         323
1092   1426310         346
1093   1426311         314
1094   1426312         227

[1095 rows x 2 columns]

In [102]:
matches.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [103]:
season_wise = match_agg.merge(matches,left_on='match_id',right_on='id')[['match_id','total_runs','season']]
season_wise

      match_id  total_runs   season
0       335982         304  2007/08
1       335983         447  2007/08
2       335984         261  2007/08
3       335985         331  2007/08
4       335986         222  2007/08
...        ...         ...      ...
1090   1426307         429     2024
1091   1426309         323     2024
1092   1426310         346     2024
1093   1426311         314     2024
1094   1426312         227     2024

[1095 rows x 3 columns]

In [118]:
trace = go.Box(x=season_wise['total_runs'],text=season_wise['season'])
data = [trace]

layout = go.Layout(title='Total Score Analysis',xaxis={'title':'Total Score'})

fig = go.Figure(data=data,layout=layout)

pyo.plot(fig)

'temp-plot.html'

In [124]:
# Two box plots based on the catogories

trace1 = go.Box(x=season_wise[season_wise['season']=='2017']['total_runs'],name='2017',marker={'color':'#00a65a'})

trace2 = go.Box(x=season_wise[season_wise['season']=='2009']['total_runs'],name='2009')

data = [trace1,trace2]

layout = go.Layout(title='Total Score Analysis',xaxis={'title':'Total Score'})

fig = go.Figure(data=data,layout=layout)

pyo.plot(fig)

python(26988) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

'temp-plot.html'

In [123]:
season_wise.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1095 entries, 0 to 1094
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   match_id    1095 non-null   int64
 1   total_runs  1095 non-null   int64
 2   season      1095 non-null   object
dtypes: int64(2), object(1)
memory usage: 34.2+ KB

## Distplot

- Distribution Plot
- Continious variable

In [125]:
import plotly.figure_factory as ff

In [126]:
avg

            batter        avg  batsman_runs
0   AB de Villiers  39.853846    148.580442
1       AD Russell  28.930233    164.224422
2         AJ Finch  24.904762    123.349057
3        AM Rahane  30.142857    120.321410
4        AT Rayudu  28.051613    124.584527
5      BB McCullum  27.711538    126.848592
6         CH Gayle  39.658730    142.121729
7        DA Miller  35.658537    134.684477
8        DA Warner  40.042683    135.429986
9         DR Smith  28.392857    132.279534
10    F du Plessis  35.992126    133.071325
11       G Gambhir  31.007353    119.665153
12      GJ Maxwell  24.750000    150.488599
13       HH Pandya  28.471910    139.691290
14    Ishan Kishan  28.430108    132.797589
15      JC Buttler  37.715789    142.238984
16       JH Kallis  28.552941    105.936272
17      KA Pollard  28.404959    140.457703
18      KD Karthik  26.320652    131.353404
19        KL Rahul  44.657143    131.050866
20   KS Williamson  35.533333    122.952710
21         M Vijay  25.930693    118.614130
22      MA Agarwal  22.811966    128.255646
23       MK Pandey  29.015038    117.366180
24        MS Dhoni  39.126866    132.835065
25          N Rana  28.344086    130.818859
26        PA Patel  22.603175    116.625717
27       Q de Kock  30.980392    131.120332
28        R Dravid  28.233766    113.347237
29       RA Jadeja  27.398148    124.432296
30     RA Tripathi  26.939759    135.515152
31      RD Gaikwad  41.754386    133.632791
32       RG Sharma  29.730942    127.918194
33         RR Pant  35.451613    143.597561
34      RV Uthappa  27.522222    126.152279
35        S Dhawan  35.072539    123.454313
36        SA Yadav  31.805310    142.505948
37        SE Marsh  39.507937    130.109775
38        SK Raina  32.374269    132.535312
39       SPD Smith  34.652778    124.812406
40    SR Tendulkar  33.826087    114.187867
41       SR Watson  30.793651    134.163209
42         SS Iyer  31.948980    123.025540
43       SV Samson  30.687500    135.137615
44    Shubman Gill  37.835294    132.236842
45         V Kohli  38.714976    128.511867
46        V Sehwag  27.555556    148.827059
47         WP Saha  24.247934    123.902027
48       YK Pathan  29.290909    138.046272
49    Yuvraj Singh  24.810811    124.784776

In [138]:
hist_data = [avg['avg'],avg['batsman_runs']]
group_labels = ['Average','Batsman Runs']
fig = ff.create_distplot(hist_data,group_labels,bin_size=[10,20])
pyo.plot(fig)

python(27732) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

'temp-plot.html'

In [128]:
hist_data = avg['avg']

[0     39.853846
 1     28.930233
 2     24.904762
 3     30.142857
 4     28.051613
 5     27.711538
 6     39.658730
 7     35.658537
 8     40.042683
 9     28.392857
 10    35.992126
 11    31.007353
 12    24.750000
 13    28.471910
 14    28.430108
 15    37.715789
 16    28.552941
 17    28.404959
 18    26.320652
 19    44.657143
 20    35.533333
 21    25.930693
 22    22.811966
 23    29.015038
 24    39.126866
 25    28.344086
 26    22.603175
 27    30.980392
 28    28.233766
 29    27.398148
 30    26.939759
 31    41.754386
 32    29.730942
 33    35.451613
 34    27.522222
 35    35.072539
 36    31.805310
 37    39.507937
 38    32.374269
 39    34.652778
 40    33.826087
 41    30.793651
 42    31.948980
 43    30.687500
 44    37.835294
 45    38.714976
 46    27.555556
 47    24.247934
 48    29.290909
 49    24.810811
 Name: avg, dtype: float64]

## Histogram
- A histogram is a plot that lets you discover and show the underlying frequency distribution (shape) of a set of continious data

In [144]:
x = delivery.groupby('batter')['batsman_runs'].count()>150
x = x[x].index.to_list()
x

['A Ashish Reddy',
 'A Badoni',
 'A Manohar',
 'A Mishra',
 'A Symonds',
 'AA Jhunjhunwala',
 'AB Agarkar',
 'AB de Villiers',
 'AC Gilchrist',
 'AD Mathews',
 'AD Russell',
 'AJ Finch',
 'AK Markram',
 'AL Menaria',
 'AM Nayar',
 'AM Rahane',
 'AP Tare',
 'AR Patel',
 'AS Raut',
 'AT Rayudu',
 'Abdul Samad',
 'Abhishek Sharma',
 'Abishek Porel',
 'Anuj Rawat',
 'Atharva Taide',
 'Azhar Mahmood',
 'B Chipli',
 'B Kumar',
 'B Sai Sudharsan',
 'BA Stokes',
 'BB McCullum',
 'BJ Hodge',
 'C Green',
 'C de Grandhomme',
 'CA Ingram',
 'CA Lynn',
 'CA Pujara',
 'CH Gayle',
 'CH Morris',
 'CJ Anderson',
 'CL White',
 'CM Gautam',
 'D Brevis',
 'D Padikkal',
 'DA Miller',
 'DA Warner',
 'DB Das',
 'DB Ravi Teja',
 'DJ Bravo',
 'DJ Hooda',
 'DJ Hussey',
 'DJ Mitchell',
 'DJG Sammy',
 'DP Conway',
 'DPMD Jayawardene',
 'DR Smith',
 'DT Christian',
 'DW Steyn',
 'Dhruv Jurel',
 'E Lewis',
 'EJG Morgan',
 'F du Plessis',
 'FY Fazal',
 'G Gambhir',
 'GC Smith',
 'GH Vihari',
 'GJ Bailey',
 'GJ Maxwell',
 'Gurkeerat Singh',
 'H Klaasen',
 'HC Brook',
 'HH Gibbs',
 'HH Pandya',
 'HM Amla',
 'HV Patel',
 'Harbhajan Singh',
 'Harpreet Brar',
 'IK Pathan',
 'Ishan Kishan',
 'J Botha',
 'JA Morkel',
 'JC Buttler',
 'JD Ryder',
 'JD Unadkat',
 'JEC Franklin',
 'JH Kallis',
 'JJ Roy',
 'JM Bairstow',
 'JM Sharma',
 'JO Holder',
 'JP Duminy',
 'JP Faulkner',
 'JR Hopes',
 'K Goel',
 'K Gowtham',
 'K Rabada',
 'KA Pollard',
 'KC Sangakkara',
 'KD Karthik',
 'KH Pandya',
 'KK Nair',
 'KL Rahul',
 'KM Jadhav',
 'KP Pietersen',
 'KR Mayers',
 'KS Bharat',
 'KS Williamson',
 'KV Sharma',
 'Kuldeep Yadav',
 'LA Pomersbach',
 'LMP Simmons',
 'LR Shukla',
 'LRPL Taylor',
 'LS Livingstone',
 'Lalit Yadav',
 'M Kaif',
 'M Manhas',
 'M Shahrukh Khan',
 'M Vijay',
 'M Vohra',
 'MA Agarwal',
 'MC Henriques',
 'MD Mishra',
 'MEK Hussey',
 'MG Johnson',
 'MJ Guptill',
 'MJ Lumb',
 'MK Lomror',
 'MK Pandey',
 'MK Tiwary',
 'ML Hayden',
 'MM Ali',
 'MN Samuels',
 'MP Stoinis',
 'MR Marsh',
 'MS Bisla',
 'MS Dhoni',
 'MS Wade',
 'MV Boucher',
 'Mandeep Singh',
 'Mohammad Nabi',
 'N Jagadeesan',
 'N Pooran',
 'N Rana',
 'N Wadhera',
 'NLTC Perera',
 'NV Ojha',
 'Nithish Kumar Reddy',
 'OA Shah',
 'P Kumar',
 'P Negi',
 'P Simran Singh',
 'PA Patel',
 'PA Reddy',
 'PBB Rajapaksa',
 'PC Valthaty',
 'PD Collingwood',
 'PD Salt',
 'PJ Cummins',
 'PK Garg',
 'PP Chawla',
 'PP Shaw',
 'Q de Kock',
 'R Ashwin',
 'R Bhatia',
 'R Dhawan',
 'R Dravid',
 'R McLaren',
 'R Parag',
 'R Powell',
 'R Sathish',
 'R Tewatia',
 'R Vinay Kumar',
 'RA Jadeja',
 'RA Tripathi',
 'RD Gaikwad',
 'RG Sharma',
 'RK Singh',
 'RM Patidar',
 'RN ten Doeschate',
 'RR Pant',
 'RR Rossouw',
 'RS Bopara',
 'RV Uthappa',
 'Rahmanullah Gurbaz',
 'Rashid Khan',
 'S Badrinath',
 'S Dhawan',
 'S Dube',
 'S Gopal',
 'S Sohal',
 'SA Asnodkar',
 'SA Yadav',
 'SC Ganguly',
 'SE Marsh',
 'SK Raina',
 'SK Warne',
 'SM Curran',
 'SM Katich',
 'SN Khan',
 'SN Thakur',
 'SO Hetmyer',
 'SP Fleming',
 'SP Goswami',
 'SP Narine',
 'SPD Smith',
 'SR Tendulkar',
 'SR Watson',
 'SS Iyer',
 'SS Tiwary',
 'ST Jayasuriya',
 'STR Binny',
 'SV Samson',
 'SW Billings',
 'Salman Butt',
 'Shahbaz Ahmed',
 'Shakib Al Hasan',
 'Shashank Singh',
 'Shubman Gill',
 'T Stubbs',
 'TH David',
 'TL Suman',
 'TM Dilshan',
 'TM Head',
 'Tilak Varma',
 'UBT Chand',
 'UT Yadav',
 'V Kohli',
 'V Sehwag',
 'V Shankar',
 'VR Iyer',
 'VVS Laxman',
 'WP Saha',
 'Washington Sundar',
 'Y Nagar',
 'Y Venugopal Rao',
 'YBK Jaiswal',
 'YK Pathan',
 'YV Takawale',
 'Yuvraj Singh']

In [145]:
new = delivery[delivery['batter'].isin(x)]

runs = new.groupby('batter')['batsman_runs'].sum()
balls = new.groupby('batter')['batsman_runs'].count()

In [146]:
runs

batter
A Ashish Reddy      280
A Badoni            634
A Manohar           231
A Mishra            381
A Symonds           974
                   ...
Y Venugopal Rao     985
YBK Jaiswal        1607
YK Pathan          3222
YV Takawale         192
Yuvraj Singh       2754
Name: batsman_runs, Length: 240, dtype: int64

In [147]:
balls

batter
A Ashish Reddy      196
A Badoni            505
A Manohar           181
A Mishra            440
A Symonds           781
                   ...
Y Venugopal Rao     865
YBK Jaiswal        1095
YK Pathan          2334
YV Takawale         183
Yuvraj Singh       2207
Name: batsman_runs, Length: 240, dtype: int64

In [148]:
sr = (runs/balls) * 100
sr

batter
A Ashish Reddy     142.857143
A Badoni           125.544554
A Manohar          127.624309
A Mishra            86.590909
A Symonds          124.711908
                      ...
Y Venugopal Rao    113.872832
YBK Jaiswal        146.757991
YK Pathan          138.046272
YV Takawale        104.918033
Yuvraj Singh       124.784776
Name: batsman_runs, Length: 240, dtype: float64

In [149]:
sr = sr.reset_index()
sr

              batter  batsman_runs
0     A Ashish Reddy    142.857143
1           A Badoni    125.544554
2          A Manohar    127.624309
3           A Mishra     86.590909
4          A Symonds    124.711908
..               ...           ...
235  Y Venugopal Rao    113.872832
236      YBK Jaiswal    146.757991
237        YK Pathan    138.046272
238      YV Takawale    104.918033
239     Yuvraj Singh    124.784776

[240 rows x 2 columns]

In [151]:
trace = go.Histogram(x=sr['batsman_runs'],name="Strike run variation")
data = [trace]
layout = go.Layout(title='Strike Rate Analysis',xaxis={'title':'Strike Rates'})

fig = go.Figure(data=data,layout=layout)
pyo.plot(fig)

python(28132) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

'temp-plot.html'

## Heatmaps
- Heatmap is a graphical representation of data

In [152]:
six=delivery[delivery['batsman_runs']==6]
six=six.groupby(['batting_team','over'])['batsman_runs'].count().reset_index()

six

            batting_team  over  batsman_runs
0    Chennai Super Kings     0             9
1    Chennai Super Kings     1            36
2    Chennai Super Kings     2            67
3    Chennai Super Kings     3            71
4    Chennai Super Kings     4            75
..                   ...   ...           ...
371  Sunrisers Hyderabad    15            56
372  Sunrisers Hyderabad    16            59
373  Sunrisers Hyderabad    17            73
374  Sunrisers Hyderabad    18            94
375  Sunrisers Hyderabad    19            79

[376 rows x 3 columns]

In [154]:
# Plot Heatmap

trace=go.Heatmap(x=six['batting_team'],y=six['over'],z=six['batsman_runs'])

data=[trace]

layout=go.Layout(title='Six Heatmap')

fig=go.Figure(data=data,layout=layout)

pyo.plot(fig)

python(28704) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

'temp-plot.html'

In [155]:
# Side by Side Heatmap

dots=delivery[delivery['batsman_runs']==0]
dots=dots.groupby(['batting_team','over'])['batsman_runs'].count().reset_index()

from plotly import tools

trace1=go.Heatmap(x=six['batting_team'],y=six['over'],
                 z=six['batsman_runs'].values.tolist())

trace2=go.Heatmap(x=dots['batting_team'],y=dots['over'],
                 z=dots['batsman_runs'].values.tolist())


fig=tools.make_subplots(rows=1,cols=2,subplot_titles=["6's","0's"], shared_yaxes=True)

fig.append_trace(trace1,1,1)
fig.append_trace(trace2,1,2)

pyo.plot(fig)

/opt/anaconda3/envs/plotlydashenv/lib/python3.8/site-packages/plotly/tools.py:455: DeprecationWarning:

plotly.tools.make_subplots is deprecated, please use plotly.subplots.make_subplots instead

python(28756) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

'temp-plot.html'

In [156]:
avg

            batter        avg  batsman_runs
0   AB de Villiers  39.853846    148.580442
1       AD Russell  28.930233    164.224422
2         AJ Finch  24.904762    123.349057
3        AM Rahane  30.142857    120.321410
4        AT Rayudu  28.051613    124.584527
5      BB McCullum  27.711538    126.848592
6         CH Gayle  39.658730    142.121729
7        DA Miller  35.658537    134.684477
8        DA Warner  40.042683    135.429986
9         DR Smith  28.392857    132.279534
10    F du Plessis  35.992126    133.071325
11       G Gambhir  31.007353    119.665153
12      GJ Maxwell  24.750000    150.488599
13       HH Pandya  28.471910    139.691290
14    Ishan Kishan  28.430108    132.797589
15      JC Buttler  37.715789    142.238984
16       JH Kallis  28.552941    105.936272
17      KA Pollard  28.404959    140.457703
18      KD Karthik  26.320652    131.353404
19        KL Rahul  44.657143    131.050866
20   KS Williamson  35.533333    122.952710
21         M Vijay  25.930693    118.614130
22      MA Agarwal  22.811966    128.255646
23       MK Pandey  29.015038    117.366180
24        MS Dhoni  39.126866    132.835065
25          N Rana  28.344086    130.818859
26        PA Patel  22.603175    116.625717
27       Q de Kock  30.980392    131.120332
28        R Dravid  28.233766    113.347237
29       RA Jadeja  27.398148    124.432296
30     RA Tripathi  26.939759    135.515152
31      RD Gaikwad  41.754386    133.632791
32       RG Sharma  29.730942    127.918194
33         RR Pant  35.451613    143.597561
34      RV Uthappa  27.522222    126.152279
35        S Dhawan  35.072539    123.454313
36        SA Yadav  31.805310    142.505948
37        SE Marsh  39.507937    130.109775
38        SK Raina  32.374269    132.535312
39       SPD Smith  34.652778    124.812406
40    SR Tendulkar  33.826087    114.187867
41       SR Watson  30.793651    134.163209
42         SS Iyer  31.948980    123.025540
43       SV Samson  30.687500    135.137615
44    Shubman Gill  37.835294    132.236842
45         V Kohli  38.714976    128.511867
46        V Sehwag  27.555556    148.827059
47         WP Saha  24.247934    123.902027
48       YK Pathan  29.290909    138.046272
49    Yuvraj Singh  24.810811    124.784776

In [158]:
avg.iloc[0]

batter          AB de Villiers
avg                  39.853846
batsman_runs        148.580442
Name: 0, dtype: object

In [159]:
avg.iloc[0:2]

           batter        avg  batsman_runs
0  AB de Villiers  39.853846    148.580442
1      AD Russell  28.930233    164.224422

In [160]:
avg.loc[0]

batter          AB de Villiers
avg                  39.853846
batsman_runs        148.580442
Name: 0, dtype: object

In [161]:
avg.loc[0:2]

           batter        avg  batsman_runs
0  AB de Villiers  39.853846    148.580442
1      AD Russell  28.930233    164.224422
2        AJ Finch  24.904762    123.349057